spring:

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:devidend;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  redis:
    host: localhost
    port: 6379

  jwt:
    secret: c3ByaW5nLXNlY3VyaXR5LXRlc3Q

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"